### ISSUE TITLE
Issue with pathgen

### ISSUE THREAD

**Issue by Voelundr** [CravateRouge/bloodyAD#18]
pathgen.py is not working for me.

The stacktrace:
```
Traceback (most recent call last):
  File "/home/kali/WINDOWS/tools/bloodyAD/pathgen.py", line 36, in <module>
    main()
  File "/home/kali/WINDOWS/tools/bloodyAD/pathgen.py", line 21, in main
    db = database.Database(args.dburi, args.dbuser, args.dbpassword)
  File "/home/kali/WINDOWS/tools/bloodyAD/autobloody/database.py", line 7, in __init__
    self._prepareDb()
  File "/home/kali/WINDOWS/tools/bloodyAD/autobloody/database.py", line 20, in _prepareDb
    session.write_transaction(self._createGraph)
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/simple.py", line 432, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/simple.py", line 325, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "/home/kali/WINDOWS/tools/bloodyAD/autobloody/database.py", line 63, in _createGraph
    graph_exists = tx.run("RETURN gds.graph.exists('autobloody')").single()[0]
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/transaction.py", line 141, in run
    result._tx_ready_run(query, parameters, **kwparameters)
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/result.py", line 70, in _tx_ready_run
    self._run(query, parameters, None, None, None, None, **kwparameters)
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/result.py", line 117, in _run
    self._attach()
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/work/result.py", line 206, in _attach
    self._connection.fetch_message()
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/io/_common.py", line 188, in inner
    func(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/io/_bolt4.py", line 306, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/home/kali/.local/lib/python3.10/site-packages/neo4j/io/_common.py", line 246, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: Unknown function 'gds.graph.exists' (line 1, column 8 (offset: 7))
"RETURN `gds`.`graph`.`exists`(("autobloody")) AS `gds.graph.exists('autobloody')`"
```

My installed python libs:
```
neo4j                          4.4.5
neo4j-driver                   4.4.5
neobolt                        1.7.17
```

**Comment by CravateRouge** [comment]
You also need to install the GDS library see: https://neo4j.com/docs/graph-data-science/current/installation/neo4j-server/
as mentioned in the requirements in the README
